### ISSUE TITLE
Error Reporting in Rake tasks

### ISSUE THREAD

**Issue by nikz** [MindscapeHQ/raygun4ruby#60]

**Comment by holgersindbaek** [comment]
@nikz How would you go about this? Is it possible currently?

**Comment by nikz** [comment]
@holgersindbaek I think you'd just need to manually `rescue` and call `Raygun.track`, but this issue was mostly a note to myself to check it works :smile: 

If you're loading `environment` in a Rails app you should be good to go.

**Comment by holgersindbaek** [comment]
Ya. That's what I'm trying to avoid. It's not possible to make an catch all rescue method specifically for rake tasks?!

-- 

All the best

Holger Sindbaek

 · UI/UX

 Designer & Web/iOS Programmer 

·

 

http://holgersindbaek.com/

On Wed, 09 Mar 2016 at 07:44 Nik Wakelin

<
mailto:Nik Wakelin <notifications@github.com>
> wrote:

https://github.com/holgersindbaek
I think you'd just need to manually

rescue

and call

Raygun.track

, but this issue was mostly a note to myself to check it works

If you're loading

environment

in a Rails app you should be good to go.

**Comment by nikz** [comment]
Hi @holgersindbaek - in order to do that you'd need to be depending on the `environment` task. So if you're relying on the Rails environment in your task, you should be good to go!
