### ISSUE TITLE
Gracefully handle lack of API key

### ISSUE THREAD

**Issue by glenngillen** [MindscapeHQ/raygun4ruby#62]
Raising an exception seems to be a very heavy handed way to warn me than my API key is missing, especially given Raygun.io isn't on the critical path to my app being available :(

https://github.com/MindscapeHQ/raygun4ruby/blob/master/lib/raygun/client.rb#L23

Any chance we could have it log to `STDERR` instead and just do nothing with any exceptions raised?

**Comment by nikz** [comment]
Hi Glenn,

Hmm - it's a balance between making it obvious how to get set up and not causing errors I guess!

We could always raise in the development env and print a warning in production - are you using RG4R in a Rails app?

Nik

**Comment by glenngillen** [comment]
Hey Nik,

I just don't think it should raise at all given this isn't a critical dependency with regards to making my product or service available to customers. Fwiw there's a lot of prior art/competition in this space and from what I can tell Raygun is the only one that raises like this. The production raise approach also doesn't get around the fact that I might not want to have exceptions logged to Raygun on a staging box (which would be running in "production" mode as far as Rack is concerned).

And... I discovered this on a production server because I removed the key to stop reporting exceptions before I deployed the code change :( Which caused an outage.

G
PS. to answer your question, it's a Sinatra app.

**Comment by nikz** [comment]
Hi Glenn,

You can configure the exception reporting using `config.enable_reporting`, so just set that to false for your staging server (you could use some other env variable or method of distinguishing a staging server from a production server rather than the Rack environment).

I'd be happy to accept a patch that takes out the exception raise, otherwise I'll make the change next time I'm doing some work on the Gem.

Cheers,

Nik

**Comment by nikz** [comment]
Hi Glenn,

Are you able to try out [this PR](https://github.com/MindscapeHQ/raygun4ruby/pull/63) for me? Should do what you're asking for.

Cheers,

Nik
