### ISSUE TITLE
Asynchronous issue reporter?

### ISSUE THREAD

**Issue by phyllisstein** [MindscapeHQ/raygun4ruby#66]
Hi there! I was wondering if there's any accepted way to configure Raygun to do its logging in an out-of-band process, like an ActiveJob worker. A cursory glance at `lib/raygun.rb` suggests it wouldn't be _too_ hard to monkey-patch that kind of thing in, but I don't want to reinvent anything that's already on a roll. Thanks in advance for your help!

**Comment by nikz** [comment]
Hi there! 

Nope, there's nothing at the moment. Part of the rationale would be to limit the number of components involved in error reporting (e.g if there's a Redis connection error and you're using a Resque/Sidekiq backend, you'll end up hitting failsafe rather than reporting)

Having said that, I'd be more than happy to accept an ActiveJob compatible patch - perhaps a config setting that accepts `async_reporting_backend = :active_job` or similar? Keeping in mind that we still need to support Rails versions that don't contain ActiveJob.

Feel free to ping me if you need any help :)

Thanks!

Nik

**Comment by phyllisstein** [comment]
That makes sense. I'll try to find the time to submit the PR you suggested, instead of just hacking something in locally. Thanks Nik!

**Comment by nikz** [comment]
No worries - even if you just hack something and submit it we can work together to get it merged in.
