### ISSUE TITLE
1.1.7 on rubygems missing testable.rb

### ISSUE THREAD

**Issue by snowblink** [MindscapeHQ/raygun4ruby#75]
For some reason, the gem on rubygems for 1.1.7 is just missing `lib/raygun/testable.rb`

**Comment by tache** [comment]
I second this error.

**Comment by jamiepenney** [comment]
Hey guys,

Sorry about that, I built the gem on my Windows machine and it turns out that doesn't work on other platforms. Have pushed out a new version (which I tested on both Linux and Windows) this morning.

My apologies,  won't be that lazy in the future! Will leave this issue open for a few more days in case anyone else wanders in with the same issue.

**Comment by tache** [comment]
I just updated, and it seems to work - Appreciate you fixing this over the weekend!

**Comment by jamiepenney** [comment]
@tache I cheated, it's Monday morning here in New Zealand.

**Comment by snowblink** [comment]
Looks good. :+1:
