### ISSUE TITLE
Encoding exceptions are not logged to Raygun

### ISSUE THREAD

**Issue by nickrivadeneira** [MindscapeHQ/raygun4ruby#99]
We recently had an encoding bug that resulted in Raygun itself raising an exception. This exception was not logged with our Raygun account, and thus we never found out about it until we happened to be looking through our logs. I was hoping that when Raygun raises an exception while logging our bug, we'd at least get some record of that in our Raygun account.

Here's a snippet of the backtrace from our logs:
```
2016-12-16T16:15:59Z  Completed 500 Internal Server Error in 54ms (ActiveRecord: 16.2ms | Elasticsearch: 0.0ms)
2016-12-16T16:15:59Z  [Raygun] Tracking Exception...
2016-12-16T16:15:59Z  JSON::GeneratorError (source sequence is illegal/malformed utf-8):
2016-12-16T16:15:59Z    vendor/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:224:in `generate'
2016-12-16T16:15:59Z    vendor/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:224:in `generate'
2016-12-16T16:15:59Z    vendor/bundle/ruby/2.3.0/gems/raygun4ruby-1.1.11/lib/raygun/client.rb:167:in `create_entry'
2016-12-16T16:15:59Z    vendor/bundle/ruby/2.3.0/gems/raygun4ruby-1.1.11/lib/raygun/client.rb:27:in `track_exception'
2016-12-16T16:15:59Z    vendor/bundle/ruby/2.3.0/gems/raygun4ruby-1.1.11/lib/raygun.rb:43:in `track_exception'
2016-12-16T16:15:59Z    vendor/bundle/ruby/2.3.0/gems/raygun4ruby-1.1.11/lib/raygun/middleware/rack_exception_interceptor.rb:12:in `rescue in call'
2016-12-16T16:15:59Z    vendor/bundle/ruby/2.3.0/gems/raygun4ruby-1.1.11/lib/raygun/middleware/rack_exception_interceptor.rb:10:in `call'
```

If it's helpful at all, we fixed the bug in our application with:
```ruby
def reencode_as_utf8(string)
  string.encode(
    "utf-8",
    "binary",
    invalid: :replace,
    undef: :replace,
    replace: "",
  )
end
```

**Comment by nikz** [comment]
Hi Nick,

Thanks for the comment, and apologies for the issue you had with Raygun4Ruby.

The failsafe exceptions you see there are optionally logged [out to their own logger](https://github.com/MindscapeHQ/raygun4ruby/blob/master/lib/raygun/configuration.rb#L36). We deliberately don't retry to avoid an infinite loop or similar (although we are open to suggestions to make things more robust, perhaps rescuing from a set of exceptions and triggering a failsafe log entry in Ragyun? I'm not sure if @j5alive or @CmdrKeen want to weigh in there, what do the other clients do?)

Cheers,

Nik

**Comment by nickrivadeneira** [comment]
@nikz Makes sense to avoid the infinite loop. Having talked with your support team about the issue, Yosan said this about the Raygun4Net library:

> ...any problems that occur in Raygun4Net are caught so that they don't cause problems with the application.

and:

> If your application was using the raygun4net provider, there is an option to change the behaviour so errors coming from raygun4net will get thrown. In RaygunSettings there is a configuration option called "throwOnError". You can set this in the web.config settings, e.g. `<RaygunSettings apikey="YOUR_APP_API_KEY" throwOnError="true" />`

I don't want to speak on behalf of other raygun4ruby users, but a useful default in our case would be to log to Rails logger with the message [here](https://github.com/MindscapeHQ/raygun4ruby/blob/13b31a4459cc00a42007257e34d0d4ef1f06801a/lib/raygun.rb#L47) rather than `raise` the Raygun exception in our app. With a well-defined message that is logged, we could catch it in our logging service (Papertrail). We'd have an alert that is sent out for regex matches on `Problem reporting exception to Raygun` in our logs.

One final thing is that the config options aren't documented anywhere other than the source. That seems OK since they are documented nicely there, but it would be good to have a link to that file from the README. I would have never known the `failsafe_logger` option existed unless I started digging into the source.

**Comment by UberMouse** [comment]
Hey @nickrivadeneira,

For your first point, I suspect the reason that isn't done is because it's designed to support non-rails Ruby installations. Maybe we can add some logic to detect when it's running in a Rails environment in the configuration and have it automatically hook up the `failsafe_logger` to the Rails logger however. Just want to confirm also that the `failsafe_logger` option resolved your use case of catching this issue in Papertrail?

As for your second point, I've added a link to the `configuration.rb` file at the bottom of the README so that people are aware that there may be more configuration options they may want to configure than just what the README surfaces.

I'm also thinking that it might make sense to add some logic to try a single time to send the exception Raygun raises back to Raygun so you get notified if raygun4ruby crashes trying to report an exception. In this case, I think that would have reported the raygun4ruby error correctly as it was the exception itself causing raygun4ruby to crash, not the reporting of the exception (which is where the infinite loop would come from). But I'll need to think a bit further on that to see if it makes sense.

**Comment by nickrivadeneira** [comment]
@UberMouse 

> Just want to confirm also that the failsafe_logger option resolved your use case of catching this issue in Papertrail?

I believe so. I added it into our code at the time of original posting, so it's been a couple months. I would have only merged it in after testing it and confirming it to be working (hopefully 😁 ).

> I'm also thinking that it might make sense to add some logic to try a single time to send the exception Raygun raises back to Raygun so you get notified if raygun4ruby crashes trying to report an exception.

This sounds like a great solution - better than logging and capturing with Papertrail.
